### PR TITLE
Precompute before/after offsets and use in disambiguate_possible_epoch_nanos

### LINKED ISSUE #477: disambiguate_possible_epoch_nanos doesn't correctly do the "latest possible"/"earliest possible" steps.
Testcase taken from staging/Intl402/Temporal/old/dst-math, which currently crashes. In this testcase, an entire day is lost to a transition

```rust
    #[test]
    fn test_apia() {
        let zdt = parse_zdt_with_reject("2011-12-29T22:00:00[Pacific/Apia]").unwrap();
        // Transition: 2011-12-29T23:59:59.999999999-10:00[Pacific/Apia] to 2011-12-31T00:00:00+14:00[Pacific/Apia]
        let y = zdt.add(&Duration::new(0,0,0,1,1,0,0,0,0,0).unwrap(), None).unwrap();
    }
```

The panic is at https://github.com/boa-dev/temporal/blob/669fc9fb8ef8743c0955c61c34bbd2f4c6a04816/src/builtins/core/timezone.rs#L446-L450

The code does the following:

```rust
        // NOTE: Below is rather greedy, but should in theory work.
        //
        // Primarily moving hour +/-3 to account Australia/Troll as
        // the precision of before/after does not entirely matter as
        // long is it is distinctly before / after any transition.

        // 6. Let before be the latest possible ISO Date-Time Record for
        //    which CompareISODateTime(before, isoDateTime) = -1 and !
        //    GetPossibleEpochNanoseconds(timeZone, before) is not
        //    empty.
        let before = iso.add_date_duration(
            Calendar::default(),
            &DateDuration::default(),
            NormalizedTimeDuration(-3 * NS_IN_HOUR),
            None,
        )?;
```

which I think is incorrect.

I think what we should do is change the `Vec<EpochNanoseconds>` to something that has three variants, where the None variant includes the bounds on either end.

### PR DESCRIPTION
**Pull request by Manishearth**
Based on #478, but can just be reviewed instead of it.

Fixes #477

This adds a GapEntryOffsets type that can be used to store the offsets before/after a gap transition, which can then be used directly in disambiguate_possible_epoch_nanos.

### CODE REVIEW

File: src/provider.rs [hunk 1]
```diff
@@ -55,6 +54,62 @@ impl core::fmt::Display for TransitionDirection {
     }
 }
 
+/// Used in disambiguate_possible_epoch_nanos
+///
+/// When we have a LocalTimeRecordResult::Empty,
+/// it is useful to know the offsets before and after.
+#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
+pub struct GapEntryOffsets {
```
Comment (nekevss) [inline src/provider.rs:62]: praise: nice refactor

**Review by nekevss — APPROVED** [review]
Wow, this looks great! Also, nice to see some of the extra calls removed.
