### PR TITLE
Fix up eras, correctly expose arithmetic year

### LINKED ISSUE #423: EraYear::try_from_partial_date needs to be able to handle fully-loaded partial dates
https://github.com/boa-dev/temporal/blob/0b07cc84ce9bba5cf73251e715359fc13ecc66ed/src/builtins/core/calendar/types.rs#L94-L126

This code assumes that either you are passing in `era, eraYear` or you are passing in `year`. This code is transitively called by `PlainDate::to_plain_month_day()` (etc), which constructs an intermediate `PartialDate`, and the error in the wildcard branch is hit.

This code should probably instead supply some sort of precedence when both sets of fields are specified (note this will reliably happen whenever a PartialFoo is constructed from a full object!).

It's not 100% clear to me what the precedence is here; it seems like it is implementation-defined in [CalendarResolveFields](https://tc39.es/proposal-temporal/#sec-temporal-calendarresolvefields). I might be looking in the wrong place.

cc @sffc This may be something that should be specified further in https://tc39.es/proposal-intl-era-monthcode ?

### PR DESCRIPTION
**Pull request by Manishearth**
This does a bunch of fixes to the era code:

 - Updates the list of eras to the latest proposal-intl-era-monthcode list
 - Correctly exposes `.year()` as arithmetic year
 - Allows specifying both year and era/eraYear as long as they match
 - Adds a test for arithmetic year calculation
 - Switches over to using None eras for calendars that do not canonically have them

Fixes #423

### CODE REVIEW

File: src/builtins/core/calendar/types.rs [hunk 1]
```diff
@@ -112,13 +100,30 @@ impl EraYear {
...
                 Ok(Self {
                     year: era_year,
-                    era: Era(era_info.name),
+                    era: Some(Era(era_info.name)),
                 })
             }
+            (Some(year), None, None) => Ok(Self {
+                era: partial
+                    .calendar
+                    .get_calendar_default_era()
```
Comment (Manishearth) [inline src/builtins/core/calendar/types.rs:121]: in theory here we should be able to just pass down None; ICU4X treats None as "default era"

File: src/builtins/core/calendar/types.rs [hunk 2]
```diff
@@ -92,17 +90,7 @@ impl EraYear {
...
-                    return Err(TemporalError::r#type()
-                        .with_message("Era is required for the provided calendar."));
-                };
-                Ok(Self {
-                    era: Era(era.name),
-                    year,
-                })
-            }
-            (None, Some(era), Some(era_year)) => {
+            (maybe_year, Some(era), Some(era_year)) => {
```
Comment (Manishearth) [inline src/builtins/core/calendar/types.rs:93]: This does not yet handle cases like `(year, era, eraYear = none)` or `(year, era = None, eraYear)`. They're a bit more nonsensical; I'm not sure if we should be doing anything here.

File: src/builtins/core/calendar/types.rs [hunk 3]
```diff
@@ -112,13 +100,30 @@ impl EraYear {
                         era_info.name.as_str()
                     )));
                 }
+                // or a RangeError exception if the fields are sufficient but their values are internally inconsistent
+                // within the calendar (e.g., when fields such as [[Month]] and [[MonthCode]] have conflicting non-unset values). For example:
+                if let Some(arith) = maybe_year {
+                    let calculated_arith = era_info.arithmetic_year_for(era_year);
```
Comment (Manishearth) [inline src/builtins/core/calendar/types.rs:106]: note that this deliberately compares arithmetic years instead of trying for the default era: `(2019, reiwa, 1)` is an okay thing to specify.

File: src/builtins/core/calendar.rs [hunk 4]
```diff
@@ -566,8 +547,8 @@ impl Calendar {
             {
                 Some(era::JAPANESE_INVERSE_ERA)
             }
-            AnyCalendarKind::Japanese if *era_alias == tinystr!(19, "mejei") => {
-                Some(era::MEJEI_ERA)
+            AnyCalendarKind::Japanese if *era_alias == tinystr!(19, "meiji") => {
```
Comment (nekevss) [inline src/builtins/core/calendar.rs:550]: :scream: nice catch!

File: src/builtins/core/calendar/types.rs [hunk 5]
```diff
@@ -112,13 +100,30 @@ impl EraYear {
...
+                    if calculated_arith != arith {
+                        return Err(
+                            TemporalError::range().with_message("Conflicting era/eraYear info")
```
Comment (nekevss) [inline src/builtins/core/calendar/types.rs]: question: shouldn't this be for conflicting year and eraYear values?

**Review by nekevss — APPROVED** [review]
Looks good to me overall. I did have one question regarding an error message, but it's not necessarily blocking.

File: src/builtins/core/calendar/types.rs (hunk 5 above)
Comment (Manishearth) [reply src/builtins/core/calendar/types.rs]: ah, yes, correct. will fix when I'm back at a computer

**Review by Manishearth — COMMENTED** [review]
oops my comments never got posted
