### PR TITLE
Normalize, don't canonicalize time zones

### LINKED ISSUE #465: We shouldn't actually be canonicalizing time zones all the time
#415 was done incorrectly, and #460 made it worse.

Temporal requires time zones be _normalized_, not canonicalized, most times. `new Temporal.ZonedDateTime(0n, "Asia/Calcutta").timeZoneId` should actually return `Asia/Calcutta` even though it's a "Link" zone (with `Asia/Kolkata` being canonical.

I think we'll need a modified data model where we store normalized time zone Ids, and have a separate links table for canonicalization.

Canonicalization is only needed on `.equals()`.

I have a fair number of failures right now due to this: https://gist.github.com/Manishearth/69fd90741bc8f5f147f998a014deab71

cc @sffc

### PR DESCRIPTION
**Pull request by Manishearth**
exposes separate canonicalization routines for ZonedDateTime.equals and ffi

Fixes #465

### CODE REVIEW

**Comment by Manishearth** [comment]
Some potential changes I could make:

 - Expose a `time_zone_equals` method on the provider itself so we don't have to go via strings
 - Have these methods not return a Result since time zones should already be normalized

I ended up having `equals()` still return bool over FFI since the error should not occur for normalized time zones.

**Comment by Manishearth** [comment]
cc @sffc

File: provider/src/tzdb.rs [hunk 1]
```diff
@@ -41,6 +41,9 @@ pub struct IanaIdentifierNormalizer<'data> {
     /// An index to the location of the normal identifier.
     #[cfg_attr(feature = "datagen", serde(borrow))]
     pub available_id_index: ZeroAsciiIgnoreCaseTrie<ZeroVec<'data, u8>>,
+    /// A "links" table mapping non-canonical IDs to their canonical IDs
+    #[cfg_attr(feature = "datagen", serde(borrow))]
+    pub links: ZeroAsciiIgnoreCaseTrie<ZeroVec<'data, u8>>,
```
Comment (nekevss) [inline provider/src/tzdb.rs]: thought: is there a better name than "links"

Maybe `non_canonical_identifiers` would be a good option for this field. This is more of a nitpick/bikeshed thought than anything, so feel free to ignore it.

File: src/builtins/core/timezone.rs [hunk 2]
```diff
@@ -210,6 +210,41 @@ impl TimeZone {
...
+            }
+            TimeZone::UtcOffset(offset) => TimeZone::UtcOffset(*offset),
+        })
+    }
+
+    /// Get the primary identifier for this timezone
+    #[cfg(feature = "compiled_data")]
+    pub fn primary_identifier(&self) -> TemporalResult<Self> {
+        self.primary_identifier_with_provider(&*crate::builtins::TZ_PROVIDER)
+    }
```
Comment (nekevss) [inline src/builtins/core/timezone.rs:231]: nit: space

File: provider/src/tzdb.rs [hunk 3]
```diff
@@ -101,56 +104,56 @@ impl IanaIdentifierNormalizer<'_> {
...
-                };
+                let normalized_id = norm_vec.binary_search(id).unwrap();
+
                 (id.to_ascii_lowercase().as_bytes().to_vec(), normalized_id)
             })
             .collect();
-        identifier_map.insert(b"etc/utc".to_vec(), utc_id);
+
+        let mut primary_id_map: BTreeMap<Vec<u8>, usize> = BTreeMap::new();
+        // ECMAScript implementations must support an available named time zone with the identifier "UTC", which must be
```
Comment (nekevss) [inline provider/src/tzdb.rs:131]: thought: we really should update the name of IanaNormalizer.

I wasn't a big fan of the name at first but went with it. I was already starting to lean into naming this `AvalableNamedTimeZones`, but this PR expands the functionality even further away from just normalization.

Don't think it needs to be part of this PR but still wanted to express it.  I can open an issue for further discussion.

File: src/builtins/core/timezone.rs [hunk 4]
```diff
@@ -210,6 +210,41 @@ impl TimeZone {
...
+    // TimeZoneEquals, which compares primary identifiers
+    pub(crate) fn time_zone_equals_with_provider(
+        &self,
+        other: &Self,
+        provider: &impl TimeZoneProvider,
+    ) -> TemporalResult<bool> {
+        Ok(match (self, other) {
+            (TimeZone::IanaIdentifier(one), TimeZone::IanaIdentifier(two)) => {
+                let one = provider.canonicalize_identifier(one.as_bytes())?;
```
Comment (nekevss) [inline src/builtins/core/timezone.rs:241]: hmmmmm, I'm not against with merging this as is for now.

I wasn't entirely sure when I read the comment about adding an equals method to the provider, but canonical equality (so to speak) is based on how the underlying data.

Comment (Manishearth) [reply src/builtins/core/timezone.rs:241]: Yeah. I think that might be a change worth doing in a followup, and we can refine as we refine the timezone data model.

File: provider/src/tzdb.rs (hunk 3 above)
Comment (justingrant) [reply provider/src/tzdb.rs:131]: If this does what `AvalableNamedTimeZones` does in the Temporal spec, then I agree that a name change may make sense.
